= Cahier De Recette - DailyBankApp
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe:  

Créé par : 
Créé pour :  

 



== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour ...


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur capable d'executer Java 17 et JavaFX.
Peu importe le système d'exploitation.
(Nous avons implémenter un systeme permettant d'important un livrable .jar pour toute les platefromes, Windows, Linux, MacOs.)



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK


5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====




|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK

|====


==== 1.2 Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Créer un compte
>|Objectif 4+| Vérifier qu'il est possible de créer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1     ^|Sélectionner le bouton nouveau compte. ^|la page de création de compte s'ouvre  ^| ... ^| OK

5+|

5+|Commentaire :|

|====

|====

>|Cas de test 4+|Test-01-02-05
>|Titre 4+|Cloturer un compte
>|Objectif 4+| Vérifier qu'il est possible de cloturer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1    ^|Sélectionner le bouton cloturer. ^|la page de cloturation de compte s'ouvre  ^| avoir sélectionné un compte dans la liste  ^| OK

^|All_G_CB.2    ^|cliquer sur le bouton cloturer sur la page de cloturation. ^|la page de cloturation se ferme et le compte se mets en état cloturé et ne se supprime pas de la base de donnée  ^| le compte doit avoir un solde inférieur ou égal à 0 ^| OK

5+|

5+|Commentaire :|

|====


==== 1.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Crédit". ^|La page des crédit du compte s’affiche. ^| Un compte non cloturé est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| 
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est +150 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| 
 ^|OK
 
  
 

|====


|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Virement d'un compte à l'autre
>|Objectif 4+| Vérifier qu'il est possible de faire un virement entre deux comptes d'un même client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Effectuer virement". ^|La page des virements s’affiche. ^| Un compte non cloturé est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde du compte saisie est +50euros et le nouveau solde du compte sélectionné de base est de -50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +50 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde du compte saisie est +150euros et le nouveau solde du compte sélectionné de base est de -150euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +150 euros.
 ^|OK
 
  
 

|====

|====

>|Cas de test 4+|Test-01-03-04
>|Titre 4+|Débiter un compte même si il y a un dépassement de Découvert Autorisé
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte même si il y a un dépassement de Découvert autorisé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche avec un bouton "Débit exceptionnel". ^| Un compte actif est sélectionné et l'utilisateur est chef d'agence ^|OK
^|All_G_COP.2  ^|Rentrer un montant 5000 dans le champ "Montant". ^|Le nouveau solde est -5000euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le débit exceptionnel est sélectionné et l'utilisateur est chef d'agence
 ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est -50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date et l'erreur de dépassement de Découvert Autorisé n'est pas renvoyée ^| Le débit exceptionnel est sélectionné et l'utilisateur est chef d'agence
 ^|OK


|====




=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire :|

|====

=== 3. CRUD Employés:
[.text-justify]
Un CRUD employés permet de créer, lire, mettre à jour et supprimer des informations relatives aux employés, offrant ainsi une gestion complète de leurs données tout au long de leur cycle de vie professionnel.

==== 3.1 Gestion des employés :

|====

>|Cas de test 4+|Test-03-01-01
>|Titre 4+|Créer un employé
>|Objectif 4+| Vérifier qu'il est possible de créer un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Nouveau Employé". ^|La page de création d'employé s'ouvre  ^|... ^| OK

5+|

5+|Commentaire :|

|====

|====

>|Cas de test 4+|Test-03-01-02
>|Titre 4+|Supprimer un employé
>|Objectif 4+| Vérifier qu'il est possible de supprimer un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Supprimer Employé". ^|La page de suppression d'employé s'ouvre  ^|un employé actif est sélectionné ^| OK

5+|

5+|Commentaire :|

|====

|====

>|Cas de test 4+|Test-03-01-03
>|Titre 4+|Voir les informations d'un employé
>|Objectif 4+| Vérifier qu'il est possible de supprimer un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Consulter Employé". ^|La page de consultation d'employé s'ouvre  ^|un employé actif est sélectionné ^| OK

5+|

5+|Commentaire :|

|====

|====

>|Cas de test 4+|Test-03-01-03
>|Titre 4+|Modifier un employé
>|Objectif 4+| Vérifier qu'il est possible de modifier un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Modifier Employé". ^|La page de modification d'employé s'ouvre  ^|un employé actif est sélectionné ^| OK

5+|

5+|Commentaire :|

|====

==== 4.1 Gestion des prélèvements automatique :

|====

>|Cas de test 4+|Test-04-01-01
>|Titre 4+|Ouverture de la page de gestion des prélèvements automatique
>|Objectif 4+| Vérifier qu'il est possible d'ouvrir la page de gestion des prélèvements automatique'

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Prélèvement". ^|La fenêtre des prélèvements s'ouvre. ^| Le compte n'est pas cloturé ^|OK

5+|

5+|Commentaire :

|====

|====

>|Cas de test 4+|Test-04-01-02
>|Titre 4+|Création d'un nouveau prélèvement automatique
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau prélèvement automatique

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau Prélèvement". ^|La fenêtre de création d'un prélèvement automatique s'ouvre. ^| ^|OK
^|All_G_C.2 ^|Cliquer sur le bouton "Ajouter". ^|Le prélèvement automatique se créer. ^| Le montant du prélèvement est supérieur à 0, la date de prélèvement est comprise entre 1 et 31 et le bénéficiaire est différent de null ^|OK

5+|

5+|Commentaire :

|====

|====

>|Cas de test 4+|Test-04-01-03
>|Titre 4+|Modification d'un prélèvement automatique
>|Objectif 4+| Vérifier qu'il est possible de modifier un prélèvement automatique

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Modifier Prélèvement". ^|La fenêtre de modification d'un prélèvement automatique s'ouvre. ^| Un prélèvement est sélectionné ^|OK
^|All_G_C.2 ^|Cliquer sur le bouton "modifier". ^|Le prélèvement automatique modifie ses critères en fonction des nouveaux saisies. ^| Le montant du prélèvement est supérieur à 0, la date de prélèvement est comprise entre 1 et 31 et le bénéficiaire est différent de null ^|OK

5+|

5+|Commentaire :

|====

|====

>|Cas de test 4+|Test-04-01-04
>|Titre 4+|Supression d'un prélèvement automatique
>|Objectif 4+| Vérifier qu'il est possible de supprimer un prélèvement automatique

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Supprimer Prélèvement". ^|La fenêtre de suppression d'un prélèvement automatique s'ouvre. ^| Un prélèvement est sélectionné ^|OK
^|All_G_C.2 ^|Cliquer sur le bouton "Supprimer". ^|Le prélèvement automatique se supprime et disparait de la base de donnée. ^| ^|OK

5+|

5+|Commentaire :

|====

|====

>|Cas de test 4+|Test-04-01-05
>|Titre 4+|Effectuer un prélèvement automatique
>|Objectif 4+| Vérifier qu'il est possible d'exécuter un prélèvement automatique

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Lancer le batch". ^|Le compte est débité de la somme du prélèvement automatique et l'action s'enregistre dans la liste des opérations du compte en tant que "Prélèvement Automatique". ^| La date d'occurence du prélèvement est la date du jour actuel ^|OK

5+|

5+|Commentaire :

|====




